let searchDefs = [
  {
    field_key: "subject",
    name: "subject",
    label: "Subject:",
    type: "varchar",
    value: "",
  },
  // {
  //   field_key: "date",
  //   name: "date",
  //   label: "Date:",
  //   type: "datetimecombo",
  //   options: {
  //     " ": "None",
  //     "=": "Equals",
  //     not_equal: "Not On",
  //     greater_than: "After",
  //     less_than: "Before",
  //     last_7_days: "Last 7 Days",
  //     next_7_days: "Next 7 Days",
  //     last_30_days: "Last 30 Days",
  //     next_30_days: "Next 30 Days",
  //     last_month: "Last Month",
  //     this_month: "This Month",
  //     next_month: "Next Month",
  //     last_year: "Last Year",
  //     this_year: "This Year",
  //     next_year: "Next Year",
  //     between: "Is Between",
  //   },
  //   value: "",
  // },
  // {
  //   field_key: "date",
  //   name: "datetime",
  //   label: "Date:",
  //   type: "date",
  //   value: "",
  // },
  {
    field_key: "from",
    name: "from",
    label: "From:",
    type: "varchar",
    value: "",
  },
  {
    field_key: "to",
    name: "to",
    label: "To:",
    type: "varchar",
    value: "",
  },
  // {
  //   field_key: "flagged",
  //   name: "flagged",
  //   label: "Is Favorite:",
  //   type: "bool",
  //   value: "",
  // },
  // {
  //   field_key: "seen",
  //   name: "seen",
  //   label: "Is Read:",
  //   type: "bool",
  //   value: "",
  // },
];

export { searchDefs };
