import Login from "./login";
import Dashboard from "./dashboard";
import Module from "./module";
import Edit from "./edit";
import Detail from "./detail";
import Demo from "./demo";
import Admin from "./admin";
import PortalAdminListView from "./portaladminlistview";
import PortalAdminEditView from "./portaladmineditview";
export { Login, Dashboard, Module, Edit, Detail, Demo,Admin,PortalAdminListView,PortalAdminEditView};
