import { makeStyles } from "@material-ui/styles";

export default makeStyles((theme) => ({
  btn: {
    height: "35px",
    width: "50px",
    marginRight: "10px",
  },
  sendBtn: {
    height: "35px",
    width: "auto",
    marginRight: "10px",
    padding: "0px 10px",
  },
  toButtons: {
    display: "flex",
    justifyContent: "flex-end  ",
    fontSize: "0.7rem",
    textDecoration: "underline",
    paddingRight: "10px",
    gap: "5px",
    color: theme.palette.primary.main,
    cursor: "pointer",
  },
  heading: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  smallIcon: { padding: "2px", cursor: "pointer" },
  docIcon: { padding: "2px" },
  title: { color: "#0071d2", fontSize: "16px", padding: "0px" },
  titleIcon: {
    padding: "8px",
  },
  endAdornment: {
    display: "flex",
    position: "sticky",
    right: "10px",
  },
  inputPadding: {
    padding: 0,
  },
  sendText: { paddingRight: "5px" },
  attachmentBox: {
    display: "flex",
    color: "#666d72",
    alignContent: "center",
    alignItems: "center",
    padding: "2px 5px 2px 10px",
    borderRadius: "5px",
    gap: "5px",
    backgroundColor: "#DFEDF9",
  },
  documentBox: {
    display: "flex",
    flexDirection: "row",
    gap: "5px",
    padding: "0px 7px",
    flexWrap: "wrap",
  },
  emailDraft: {
    display: "flex",
    flexDirection: "row",
    gap: "10px",
    padding: "5px 0px",
  },
  emailDraftCard: {
    color: "#6E6E6E",
    display: "flex",
    opacity: 1,
    flexDirection: "row",
    alignContent: "center",
    alignItems: "center",
    padding: "0px 10px",
    gap: "10px",
    borderRadius: "5px",
    backgroundColor: "#DFEDF9",
    cursor: "pointer",
  },
}));
