import { makeStyles } from "@material-ui/styles";

export default makeStyles((theme) => {
  return {
    mainCard: {
      borderBottom: "1px solid #dedede",
      "&:hover": {
        background: "#fafafa",
      },
    },
    iconContainer: {
      padding: "3px 6px 1px 6px",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "inherit",
      alignSelf: "start",
    },
    barIcon: {
      height: "0.8rem",
    },
    fromEmailAddr: {
      margin: "0px",
      fontSize: "12px",
      paddingLeft: "6px",
      display: "-webkit-box",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      lineHeight: "1.3",
      maxHeight: "3em",
    },
    mobileFromEmailAddr: {
      display:'block',
      margin: "0px",
      fontSize: "12px",
      wordBreak:"break-all"
    },
    iconBadge: {
      position: "relative",
      color: "#0071d2",
      background: "#0071d220",
      padding: "2px",
      height: "1.9rem",
      width: "1.9rem",
      borderRadius: "100px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: "4px",
      cursor: "pointer",
    },
    outBadge: {
      position: "absolute",
      left: "100%",
      transform: "translate(-50%, -50%)",
      background: "#FFDFD4",
      borderRadius: "50px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "4px",
      border: "1px solid white",
    },
    inBadge: {
      position: "absolute",
      left: "100%",
      transform: "translate(-50%, -50%)",
      background: "#E6FFC2",
      borderRadius: "50px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "4px",
      border: "1px solid white",
    },
    emailStatusIcon: {
      height: "0.6rem",
      width: "0.6rem",
    },
    titleWrapper: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "0px",
      width: "100%",
      padding: "4px 0px",
    },
    title: {
      color: "#0071d2",
      cursor: "pointer",
      fontSize: "14px",
      width: "100%",
      paddingLeft: "6px",
      display: "-webkit-box",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: 2,
      overflow: "hidden",
      textOverflow: "ellipsis",
      lineHeight: "1.3",
      maxHeight: "3em",
    },
    disabledTitle: {
      color: "black",
      fontSize: "14px",
      width: "100%",
      padding: "6px",
      display: "-webkit-box",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: 2,
      overflow: "hidden",
      textOverflow: "ellipsis",
      lineHeight: "1.2",
      maxHeight: "3em",
    },
    moreIcon: {
      width: "1rem",
      height: "1rem",
    },
    expandIcon: {
      height: "1.3rem",
      width: "1.4rem",
    },
    moreOptionsContainer: {
      alignSelf: "flex-start",
      display: "flex",
      justifyContent: "center",
      padding: "0px 6px 6px 6px",
    },
    otherData: {
      padding: "0px 6px 0px 6px",
      fontSize: "12px",
    },
    moreDetails: {
      display: "flex",
      alignItems: "center",
      fontSize: "12px",
      gap: "4px",
      width: "70%",
    },
    moreDetailsFull: {
      display: "flex",
      alignItems: "center",
      gap: "4px",
      fontSize: "12.8px",
      width: "100%",
    },
    moreDetailsWrapper: {
      display: "flex",
      alignItems: "center",
      gap: "4px",
      width: "100%",
    },
    chip: {
      fontSize: "12px",
      margin: "1px",
      backgroundColor: "#f4f4f4",
      width: "fit-content",
      height: "fit-content",
    },
    addrs: {
      fontSize: "12px",
      color: "#707070",
      fontWeight: "500",
      display: "flex",
      gap: "3px",
    },
    emailAddrsLabel: {
      color: "#707070",
      fontSize: "12px",
      fontWeight: "600",
    },
    description: {
      color: "black",
      fontSize: "0.8rem",
      padding: "6px",
      margin: "6px",
      transition: "height 0.3s ease-in-out",
      background: "#fafafa",
      marginTop: "0px",
      fontFamily: "Poppins",
    },
    date: {
      width: "fit-content",
      fontSize: "12px",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
      paddingLeft: "6px",
    },
    dateLabel: {
      color: "#707070",
    },
    user: {
      width: "fit-content",
      fontSize: "12px",
      whiteSpace: "nowrap",
      overflow: "hidden",
      paddingLeft: "6px",
      textOverflow: "ellipsis",
    },
    activityStatus: {
      width: "35%",
      display: "flex",
      justifyContent: "end",
      textAlign: "end",
    },
    disabledActivityStatus: {
      width: "0%",
    },
    moreOptionsWrapper: {
      border: "2px solid #0071d220",
    },
    moreOptionsList: {
      padding: "0px",
    },
    option: {
      padding: "2px 10px",
      "&:hover": {
        background: "#0071d220",
      },
    },
    optionIcon: {
      color: "#0071d2",
      marginRight: "10px",
      width: "16px",
    },
    optionLabel: {
      fontSize: "0.725rem",
    },
    statusChip: {
      borderRadius: "2px",
      padding: "3px 4px",
      marginRight: "6px",
      width: "fit-content",
      height: "fit-content",
      fontSize: "10px",
      fontWeight: "600",
      letterSpacing: "1px",
      textTransform: "uppercase",
      background: "white",
    },
    count: {
      cursor: "pointer",
      marginLeft: "4px",
      "&:hover": {
        textDecoration: "underline #0071d2",
      },
    },
    popperContent: {
      display: "flex",
      flexDirection: "column",
      boxShadow: "0px 6px 12px rgba(0, 0, 0, 0.2)",
      padding: "4px",
      zIndex: "1000",
      borderRadius: "8px",
    },
  };
});
