const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";

const FORGOT_REQUEST = "FORGOT_REQUEST";
const FORGOT_SUCCESS = "FORGOT_SUCCESS";
const FORGOT_FAILURE = "FORGOT_FAILURE";

const RESET_REQUEST = "RESET_REQUEST";
const RESET_SUCCESS = "RESET_SUCCESS";
const RESET_FAILURE = "RESET_FAILURE";

const LOGOUT_REQUEST = "LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAILURE = "LOGOUT_FAILURE";
const FORCE_LOGOUT = "FORCE_LOGOUT";

const SIDEBAR_LINKS_REQUEST = "SIDEBAR_LINKS_REQUEST";
const SIDEBAR_LINKS_SUCCESS = "SIDEBAR_LINKS_SUCCESS";
const SIDEBAR_LINKS_FAILURE = "SIDEBAR_LINKS_FAILURE";

const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";
const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
const DASHBOARD_FAILURE = "DASHBOARD_FAILURE";
const REMOVE_DASHBOARD_DATA = "REMOVE_DASHBOARD_DATA";
const DASHBOARD_TAB_RENAME = "DASHBOARD_TAB_RENAME";
const DASHBOARD_TAB_ADD = "DASHBOARD_TAB_ADD";
const SET_INITIAL_DASHBOARD_TABS = "SET_INITIAL_DASHBOARD_TABS";
const SET_DASHBOARD_TAB_INDEX = "SET_DASHBOARD_TAB_INDEX";
const SET_DASHBOARD_LAYOUT_EDITABLE = "SET_DASHBOARD_LAYOUT_EDITABLE";
const REMOVE_DASHLET_DATA = "REMOVE_DASHLET_DATA";
const ADD_DASHLET_DATA = "ADD_DASHLET_DATA";
const CHANGED_DASHLET_LAYOUT_DATA = "CHANGED_DASHLET_LAYOUT_DATA";
const SAVE_DASHLET_LAYOUT_CHANGED_POSITION =
  "SAVE_DASHLET_LAYOUT_CHANGED_POSITION";

const USER_PREFERENCE_REQUEST = "USER_PREFERENCE_REQUEST";
const USER_PREFERENCE_SUCCESS = "USER_PREFERENCE_SUCCESS";
const USER_PREFERENCE_FAILURE = "USER_PREFERENCE_FAILURE";

const FILTER_CONFIG_REQUEST = "FILTER_CONFIG_REQUEST";
const FILTER_CONFIG_SUCCESS = "FILTER_CONFIG_SUCCESS";
const FILTER_CONFIG_FAILURE = "FILTER_CONFIG_FAILURE";

const FILTER_OPEN_REQUEST = "FILTER_OPEN_REQUEST";
const FILTER_CLOSE_REQUEST = "FILTER_CLOSE_REQUEST";
const LIST_VIEW_REQUEST = "LIST_VIEW_REQUEST";
const LIST_VIEW_SUCCESS = "LIST_VIEW_SUCCESS";
const LIST_VIEW_FAILURE = "LIST_VIEW_FAILURE";

const LIST_GLOBAL_SEARCH_REQUEST = "LIST_GLOBAL_SEARCH_REQUEST";
const LIST_GLOBAL_SEARCH_SUCCESS = "LIST_GLOBAL_SEARCH_SUCCESS";

const LIST_SMART_SEARCH_REQUEST = "LIST_SMART_SEARCH_REQUEST";
const LIST_SMART_SEARCH_SUCCESS = "LIST_SMART_SEARCH_SUCCESS";

const GET_METACONFIG_REQUEST = "GET_METACONFIG_REQUEST";
const GET_METACONFIG_SUCCESS = "GET_METACONFIG_SUCCESS";
const GET_METACONFIG_FAILURE = "GET_METACONFIG_FAILURE";

const GET_CONFIG_REQUEST = "GET_CONFIG_REQUEST";
const GET_CONFIG_SUCCESS = "GET_CONFIG_SUCCESS";
const GET_CONFIG_FAILURE = "GET_CONFIG_FAILURE";

const TOGGLE_THEME = "TOGGLE_THEME";
const UPDATE_BASE_URL = "UPDATE_BASE_URL";

const GET_CURRENTUSER_REQUEST = "GET_CURRENTUSER_REQUEST";
const GET_CURRENTUSER_SUCCESS = "GET_CURRENTUSER_SUCCESS";
const GET_CURRENTUSER_FAILURE = "GET_CURRENTUSER_FAILURE";

const SET_SELECTED_MODULE = "SET_SELECTED_MODULE";

const RESET_STORE = "RESET_STORE";

const EDIT_VIEW_REQUEST = "EDIT_VIEW_REQUEST";
const EDIT_VIEW_SUCCESS = "EDIT_VIEW_SUCCESS";
const EDIT_VIEW_FAILURE = "EDIT_VIEW_FAILURE";
const STORE_ENUM_FIELD_OPTION = "STORE_ENUM_FIELD_OPTION";

const EDIT_INOUTBOUNDEMAIL_REQUEST = "EDIT_INOUTBOUNDEMAIL_REQUEST";
const EDIT_INOUTBOUNDEMAIL_SUCCESS = "EDIT_INOUTBOUNDEMAIL_SUCCESS";
const EDIT_INOUTBOUNDEMAIL_FAILURE = "EDIT_INOUTBOUNDEMAIL_FAILURE";

const SUBMIT_EDIT_VIEW_REQUEST = "SUBMIT_EDIT_VIEW_REQUEST";
const SUBMIT_EDIT_VIEW_SUCCESS = "SUBMIT_EDIT_VIEW_SUCCESS";
const SUBMIT_EDIT_VIEW_FAILURE = "SUBMIT_EDIT_VIEW_FAILURE";

const DETAIL_VIEW_REQUEST = "DETAIL_VIEW_REQUEST";
const DETAIL_VIEW_FILTER_REQUEST = "DETAIL_VIEW_FILTER_REQUEST";
const DETAIL_VIEW_SUCCESS = "DETAIL_VIEW_SUCCESS";
const DETAIL_VIEW_FILTER_SUCCESS = "DETAIL_VIEW_FILTER_SUCCESS";
const DETAIL_VIEW_FAILURE = "DETAIL_VIEW_FAILURE";

// Report Detail View
const DETAIL_GROUP_VIEW_SUCCESS = "DETAIL_GROUP_VIEW_SUCCESS";
const DETAIL_GROUP_VIEW_REQUEST = "DETAIL_GROUP_VIEW_REQUEST";
const REPORT_DETAIL_VIEW_FILTER_REQUEST = "REPORT_DETAIL_VIEW_FILTER_REQUEST";
const REPORT_DETAIL_VIEW_FILTER_SUCCESS = "REPORT_DETAIL_VIEW_FILTER_SUCCESS";
const REPORT_DETAIL_VIEW_SUCCESS = "REPORT_DETAIL_VIEW_SUCCESS";
const REPORT_DETAIL_VIEW_REQUEST = "REPORT_DETAIL_VIEW_REQUEST";
const REPORT_DETAIL_VIEW_FAILURE = "REPORT_DETAIL_VIEW_FAILURE";
const SET_REPORT_FILTER_DATA = "SET_REPORT_FILTER_DATA";

const SUBPANEL_LIST_VIEW_REQUEST = "SUBPANEL_LIST_VIEW_REQUEST";
const SUBPANEL_LIST_VIEW_SUCCESS = "SUBPANEL_LIST_VIEW_SUCCESS";
const SUBPANEL_LIST_VIEW_FAILURE = "SUBPANEL_LIST_VIEW_FAILURE";

const GET_COLUMNSCHOOSER_FIELDS_REQUEST = "GET_COLUMNSCHOOSER_FIELDS_REQUEST";
const GET_COLUMNSCHOOSER_FIELDS_SUCCESS = "GET_COLUMNSCHOOSER_FIELDS_SUCCESS";
const GET_COLUMNSCHOOSER_FIELDS_FAILURE = "GET_COLUMNSCHOOSER_FIELDS_FAILURE";

const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
const GET_NOTIFICATIONS_FAILURE = "GET_NOTIFICATIONS_FAILURE";
const SWITCH_NOTIFICATIONS_LISTENER = "SWITCH_NOTIFICATIONS_LISTENER";
const MARK_NOTIFICATION_READ_SUCCESS = "MARK_NOTIFICATION_READ_SUCCESS";
const APPEND_RECEIVE_NOTIFICATION = "APPEND_RECEIVE_NOTIFICATION";
const UPDATE_NOTIFICATION_COUNT = "UPDATE_NOTIFICATION_COUNT";
const FCM_NOTIFICATION_TOKEN = "FCM_NOTIFICATION_TOKEN";

const BPM_UPDATE_REQUEST = "BPM_UPDATE_REQUEST";
const BPM_UPDATE_SUCCESS = "BPM_UPDATE_SUCCESS";
const BPM_UPDATE_FAILURE = "BPM_UPDATE_FAILURE";

const MODULE_FIELD_TYPE_REQUEST = "MODULE_FIELD_TYPE_REQUEST";
const MODULE_FIELD_TYPE_SUCCESS = "MODULE_FIELD_TYPE_SUCCESS";
const MODULE_FIELD_TYPE_FAILURE = "MODULE_FIELD_TYPE_FAILURE";

//Email
const EMAIL_CREATE_VIEW_REQUEST = "EMAIL_CREATE_VIEW_REQUEST";
const EMAIL_CREATE_VIEW_SUCCESS = "EMAIL_CREATE_VIEW_SUCCESS";
const EMAIL_CREATE_VIEW_FAILURE = "EMAIL_CREATE_VIEW_FAILURE";

const SUBMIT_EMAIL_CREATE_VIEW_REQUEST = "SUBMIT_EMAIL_CREATE_VIEW_REQUEST";
const SUBMIT_EMAIL_CREATE_VIEW_SUCCESS = "SUBMIT_EMAIL_CREATE_VIEW_SUCCESS";
const SUBMIT_EMAIL_CREATE_VIEW_FAILURE = "SUBMIT_EMAIL_CREATE_VIEW_FAILURE";

const EMAIL_TEST_REQUEST = "EMAIL_TEST_REQUEST";
const EMAIL_TEST_SUCCESS = "EMAIL_TEST_SUCCESS";
const EMAIL_TEST_FAILURE = "EMAIL_TEST_FAILURE";

const CALENDAR_LIST_VIEW_REQUEST = "CALENDAR_LIST_VIEW_REQUEST";
const CALENDAR_LIST_VIEW_SUCCESS = "CALENDAR_LIST_VIEW_SUCCESS";
const CALENDAR_LIST_VIEW_FAILURE = "CALENDAR_LIST_VIEW_FAILURE";

const SORT_ORDER = "SORT_ORDER";
const SORT_BY = "SORT_BY";

const SUGGESTION_SUCCESS = "SUGGESTION_SUCCESS";
const SUGGESTION_FAILURE = "SUGGESTION_FAILURE";
const SUGGESTION_REQUEST = "SUGGESTION_REQUEST";

const TOGGLE_SIDEBAR_MENU = "TOGGLE_SIDEBAR_MENU";
const SET_CLEAR_BASIC_SEARCH_DATA = "SET_CLEAR_BASIC_SEARCH_DATA";
const SET_IS_FILTER_BY_BASIC_SEARCH = "SET_IS_FILTER_BY_BASIC_SEARCH";

const SAVE_INITIAL_VALUES = "SAVE_INITIAL_VALUES";

const SAVE_ENUMS_VALUES = "SAVE_ENUMS_VALUES";

const SAVE_SIDEBAR_OPEN_STATUS = "SAVE_SIDEBAR_OPEN_STATUS";
const MANAGE_SIDEBAR_FAV_STATE = "MANAGE_SIDEBAR_FAV_STATE";
const MANAGE_SIDEBAR_RECENT_STATE = "MANAGE_SIDEBAR_RECENT_STATE";

const SAVE_CONFIG_REQUEST = "SAVE_CONFIG_REQUEST";
const SAVE_CONFIG_SUCCESS = "SAVE_CONFIG_SUCCESS";
const SAVE_CONFIG_FAILURE = "SAVE_CONFIG_FAILURE";

const PORTAL_ADMIN_LINKS_REQUEST = "PORTAL_ADMIN_LINKS_REQUEST";
const PORTAL_ADMIN_LINKS_SUCCESS = "PORTAL_ADMIN_LINKS_SUCCESS";
const PORTAL_ADMIN_LINKS_FAILURE = "PORTAL_ADMIN_LINKS_FAILURE";

const PORTAL_ADMIN_MODULE_LIST_REQUEST = "PORTAL_ADMIN_MODULE_LIST_REQUEST";
const PORTAL_ADMIN_MODULE_LIST_SUCCESS = "PORTAL_ADMIN_MODULE_LIST_SUCCESS";
const PORTAL_ADMIN_MODULE_LIST_FAILURE = "PORTAL_ADMIN_MODULE_LIST_FAILURE";

const PORTAL_ADMIN_FIELD_LIST_REQUEST = "PORTAL_ADMIN_FIELD_LIST_REQUEST";
const PORTAL_ADMIN_FIELD_LIST_SUCCESS = "PORTAL_ADMIN_FIELD_LIST_SUCCESS";
const PORTAL_ADMIN_FIELD_LIST_FAILURE = "PORTAL_ADMIN_FIELD_LIST_FAILURE";

const PORTAL_ADMIN_EDIT_VIEW_REQUEST = "PORTAL_ADMIN_EDIT_VIEW_REQUEST";
const PORTAL_ADMIN_EDIT_VIEW_SUCCESS = "PORTAL_ADMIN_EDIT_VIEW_SUCCESS";
const PORTAL_ADMIN_EDIT_VIEW_FAILURE = "PORTAL_ADMIN_EDIT_VIEW_FAILURE";

const PORTAL_ADMIN_GET_EDIT_LAYOUT_REQUEST =
  "PORTAL_ADMIN_GET_EDIT_LAYOUT_REQUEST";
const PORTAL_ADMIN_GET_EDIT_LAYOUT_SUCCESS =
  "PORTAL_ADMIN_GET_EDIT_LAYOUT_SUCCESS";
const PORTAL_ADMIN_GET_EDIT_LAYOUT_FAILURE =
  "PORTAL_ADMIN_GET_EDIT_LAYOUT_FAILURE";
//studio
const SELECTED_MANAGER = "SELECTED_MANAGER";
const SELECTED_PARAMETER = "SELECTED_PARAMETER";
const RESET_DATA = "RESET_DATA";
const GET_MODULE_LIST_SUCCESS = "GET_MODULE_LIST_SUCCESS";
const GET_MODULE_LIST_FAILURE = "GET_MODULE_LIST_FAILURE";
const GET_MODULE_LIST_REQUEST = "GET_MODULE_LIST_REQUEST";
const GET_TAB_VIEW_SUCCESS = "GET_TAB_VIEW_SUCCESS";
const GET_SUBPANEL_VIEW_SUCCESS = "GET_SUBPANEL_VIEW_SUCCESS";
const GET_REL_VIEW_SUCCESS = "GET_REL_VIEW_SUCCESS";
const GET_TAB_VIEW_FAILURE = "GET_TAB_VIEW_FAILURE";
const GET_TAB_VIEW_REQUEST = "GET_TAB_VIEW_REQUEST";
const RESET_TAB_VIEW_DATA = "RESET_TAB_VIEW_DATA";
// listview redux constants
const LIST_VIEW_ON_REQUEST = "LIST_VIEW_ON_REQUEST";
const LIST_VIEW_ON_SUCCESS = "LIST_VIEW_ON_SUCCESS";
const LIST_VIEW_ON_FAILURE = "LIST_VIEW_ON_FAILURE";

export {
  LOGIN_REQUEST,
  SAVE_CONFIG_REQUEST,
  SAVE_CONFIG_SUCCESS,
  SAVE_CONFIG_FAILURE,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  CLEAR_LOGIN_ERROR,
  FORGOT_REQUEST,
  FORGOT_SUCCESS,
  GET_SUBPANEL_VIEW_SUCCESS,
  GET_REL_VIEW_SUCCESS,
  FORGOT_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,
  FORCE_LOGOUT,
  RESET_REQUEST,
  RESET_SUCCESS,
  RESET_FAILURE,
  SIDEBAR_LINKS_REQUEST,
  SIDEBAR_LINKS_SUCCESS,
  SIDEBAR_LINKS_FAILURE,
  DASHBOARD_REQUEST,
  DASHBOARD_SUCCESS,
  DASHBOARD_FAILURE,
  USER_PREFERENCE_REQUEST,
  USER_PREFERENCE_SUCCESS,
  USER_PREFERENCE_FAILURE,
  LIST_VIEW_REQUEST,
  LIST_VIEW_SUCCESS,
  LIST_VIEW_FAILURE,
  LIST_GLOBAL_SEARCH_REQUEST,
  LIST_GLOBAL_SEARCH_SUCCESS,
  LIST_SMART_SEARCH_SUCCESS,
  LIST_SMART_SEARCH_REQUEST,
  FILTER_CONFIG_REQUEST,
  FILTER_CONFIG_SUCCESS,
  FILTER_CONFIG_FAILURE,
  FILTER_OPEN_REQUEST,
  FILTER_CLOSE_REQUEST,
  GET_METACONFIG_REQUEST,
  GET_METACONFIG_SUCCESS,
  GET_METACONFIG_FAILURE,
  GET_CONFIG_REQUEST,
  GET_CONFIG_SUCCESS,
  GET_CONFIG_FAILURE,
  TOGGLE_THEME,
  GET_CURRENTUSER_REQUEST,
  GET_CURRENTUSER_SUCCESS,
  GET_CURRENTUSER_FAILURE,
  SET_SELECTED_MODULE,
  RESET_STORE,
  EDIT_VIEW_REQUEST,
  EDIT_VIEW_SUCCESS,
  EDIT_VIEW_FAILURE,
  SUBMIT_EDIT_VIEW_REQUEST,
  SUBMIT_EDIT_VIEW_SUCCESS,
  SUBMIT_EDIT_VIEW_FAILURE,
  DETAIL_VIEW_REQUEST,
  DETAIL_VIEW_FILTER_REQUEST,
  DETAIL_GROUP_VIEW_REQUEST,
  REPORT_DETAIL_VIEW_REQUEST,
  REPORT_DETAIL_VIEW_FILTER_SUCCESS,
  REPORT_DETAIL_VIEW_FILTER_REQUEST,
  REPORT_DETAIL_VIEW_SUCCESS,
  REPORT_DETAIL_VIEW_FAILURE,
  DETAIL_VIEW_SUCCESS,
  DETAIL_GROUP_VIEW_SUCCESS,
  DETAIL_VIEW_FILTER_SUCCESS,
  DETAIL_VIEW_FAILURE,
  SUBPANEL_LIST_VIEW_REQUEST,
  SUBPANEL_LIST_VIEW_SUCCESS,
  SUBPANEL_LIST_VIEW_FAILURE,
  UPDATE_BASE_URL,
  GET_COLUMNSCHOOSER_FIELDS_SUCCESS,
  GET_COLUMNSCHOOSER_FIELDS_FAILURE,
  GET_COLUMNSCHOOSER_FIELDS_REQUEST,
  GET_NOTIFICATIONS_FAILURE,
  GET_NOTIFICATIONS_REQUEST,
  GET_NOTIFICATIONS_SUCCESS,
  SWITCH_NOTIFICATIONS_LISTENER,
  MARK_NOTIFICATION_READ_SUCCESS,
  APPEND_RECEIVE_NOTIFICATION,
  UPDATE_NOTIFICATION_COUNT,
  FCM_NOTIFICATION_TOKEN,
  REMOVE_DASHLET_DATA,
  ADD_DASHLET_DATA,
  CHANGED_DASHLET_LAYOUT_DATA,
  SAVE_DASHLET_LAYOUT_CHANGED_POSITION,
  BPM_UPDATE_REQUEST,
  BPM_UPDATE_SUCCESS,
  BPM_UPDATE_FAILURE,
  MODULE_FIELD_TYPE_REQUEST,
  MODULE_FIELD_TYPE_SUCCESS,
  MODULE_FIELD_TYPE_FAILURE,
  EMAIL_CREATE_VIEW_REQUEST,
  EMAIL_CREATE_VIEW_SUCCESS,
  EMAIL_CREATE_VIEW_FAILURE,
  SUBMIT_EMAIL_CREATE_VIEW_REQUEST,
  SUBMIT_EMAIL_CREATE_VIEW_SUCCESS,
  SUBMIT_EMAIL_CREATE_VIEW_FAILURE,
  EMAIL_TEST_REQUEST,
  EMAIL_TEST_SUCCESS,
  EMAIL_TEST_FAILURE,
  CALENDAR_LIST_VIEW_REQUEST,
  CALENDAR_LIST_VIEW_SUCCESS,
  CALENDAR_LIST_VIEW_FAILURE,
  SORT_ORDER,
  SORT_BY,
  EDIT_INOUTBOUNDEMAIL_REQUEST,
  EDIT_INOUTBOUNDEMAIL_SUCCESS,
  EDIT_INOUTBOUNDEMAIL_FAILURE,
  SUGGESTION_REQUEST,
  SUGGESTION_SUCCESS,
  SUGGESTION_FAILURE,
  TOGGLE_SIDEBAR_MENU,
  SET_CLEAR_BASIC_SEARCH_DATA,
  SET_IS_FILTER_BY_BASIC_SEARCH,
  SAVE_INITIAL_VALUES,
  SAVE_ENUMS_VALUES,
  SAVE_SIDEBAR_OPEN_STATUS,
  PORTAL_ADMIN_LINKS_REQUEST,
  PORTAL_ADMIN_LINKS_SUCCESS,
  PORTAL_ADMIN_LINKS_FAILURE,
  PORTAL_ADMIN_MODULE_LIST_REQUEST,
  PORTAL_ADMIN_MODULE_LIST_SUCCESS,
  PORTAL_ADMIN_MODULE_LIST_FAILURE,
  PORTAL_ADMIN_FIELD_LIST_REQUEST,
  PORTAL_ADMIN_FIELD_LIST_SUCCESS,
  PORTAL_ADMIN_FIELD_LIST_FAILURE,
  PORTAL_ADMIN_EDIT_VIEW_REQUEST,
  PORTAL_ADMIN_EDIT_VIEW_SUCCESS,
  PORTAL_ADMIN_EDIT_VIEW_FAILURE,
  PORTAL_ADMIN_GET_EDIT_LAYOUT_REQUEST,
  PORTAL_ADMIN_GET_EDIT_LAYOUT_SUCCESS,
  PORTAL_ADMIN_GET_EDIT_LAYOUT_FAILURE,
  MANAGE_SIDEBAR_FAV_STATE,
  MANAGE_SIDEBAR_RECENT_STATE,
  SET_REPORT_FILTER_DATA,
  LIST_VIEW_ON_REQUEST,
  LIST_VIEW_ON_SUCCESS,
  LIST_VIEW_ON_FAILURE,
  SET_DASHBOARD_TAB_INDEX,
  SET_DASHBOARD_LAYOUT_EDITABLE,
  REMOVE_DASHBOARD_DATA,
  DASHBOARD_TAB_ADD,
  DASHBOARD_TAB_RENAME,
  SET_INITIAL_DASHBOARD_TABS,
  STORE_ENUM_FIELD_OPTION,
  SELECTED_PARAMETER,
  RESET_DATA,
  GET_MODULE_LIST_SUCCESS,
  GET_MODULE_LIST_FAILURE,
  GET_MODULE_LIST_REQUEST,
  GET_TAB_VIEW_SUCCESS,
  GET_TAB_VIEW_FAILURE,
  GET_TAB_VIEW_REQUEST,
  RESET_TAB_VIEW_DATA
};
